#!/bin/bash
set -euo pipefail

# 设置默认值
UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-64M}
POST_MAX_SIZE=${POST_MAX_SIZE:-64M}
MEMORY_LIMIT=${MEMORY_LIMIT:-256M}
PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-600}

# 创建PHP配置目录（如果不存在）
mkdir -p /usr/local/etc/php/conf.d

# 动态生成PHP配置文件
cat > /usr/local/etc/php/conf.d/uploads.ini << EOF
; Dynamic PHP configuration generated by docker-entrypoint.sh
; Upload settings
upload_max_filesize = ${UPLOAD_MAX_FILESIZE}
post_max_size = ${POST_MAX_SIZE}
memory_limit = ${MEMORY_LIMIT}

;# Additional upload settings
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
max_input_time = 300
max_input_vars = 3000
file_uploads = On
EOF

echo "PHP configuration generated:"
echo "  upload_max_filesize = ${UPLOAD_MAX_FILESIZE}"
echo "  post_max_size = ${POST_MAX_SIZE}"
echo "  memory_limit = ${MEMORY_LIMIT}"
echo "  max_execution_time = ${PHP_MAX_EXECUTION_TIME}"

# 调用原始的WordPress Docker入口点
exec /usr/local/bin/wordpress-entrypoint.sh "$@"